### PR TITLE
Vpl/upgrade storage sdk

### PR DESCRIPTION
**Pull request by vplauzon**
Here is an upgrade to the latest Azure.Storage.Blobs NuGet package.

That came with quite a few changes.  I do not know this code base so those changes were done quite mechanically.

**I would recommend to test thoroughly**

I fixed most unit tests but 2 files contained stuff I wasn't familiar with so I disabled their compilation.

For that and in general for the stuff I wasn't sure if I wasn't breaking anything I've put a comment with "TODO-VPL".  Please search for those to put special care.

I hope this end up being useful to upgrade anyway.

Thanks for great work on this OSS solution!

### CODE REVIEW

**Comment by chriswill** [comment]
Thanks @vplauzon for your contribution!  I will work on this a bit more and see what needs to be done to complete it.  But I really appreciate the work that you did to bring it to this point.

**Comment by vplauzon** [comment]
Hey, my pleasure Chris!

**Comment by DOMZE** [comment]
Hello @chriswill ! Do you think you will be able to get this merged soon? Is there something we can do to give you a hand?

**Comment by KrishnaKole** [comment]
Hello @chriswill, are you considering adding support for Managed identity in this? I can help to add it.

**Comment by chriswill** [comment]
@KrishnaKole I know some people were interested in Managed Identity.  If you can help add it, please create a pull request.  Also please create some documentation regarding usage and configuration for the readme.md page.  thanks

**Pull request merged**
